### PR TITLE
Fix #66 and other various fixes

### LINKED ISSUE #65: Remove duplicated WPS requests
On every selection the WPS services for unique values are called again (1 for each attribute). This is unnecessary because the WPS request is the same (no filter applied).

### LINKED ISSUE #66: Cross layer filtering on WFS takes too much on the demo
The select points takes too much to response. 
image

The data is in shape files. There should be some optimizations to perform cross layer filtering directly on db

### LINKED ISSUE #69: Snapshot sometimes appears cutted and not well sized
See the sceenshot image

### PR DESCRIPTION
**Pull request by offtherailz**
- Use png8
 - Configurable limit for selectable features (Fix #66)
 - removed duplicated WPS calls to generate advanced filters (Fix #65)
 - Snapshot improvements (Fix #69)

### CODE REVIEW

File: js/actions/featureselector.js [hunk 1]
```diff
@@ -52,8 +52,15 @@ function updateHighlightedFeatures(state, config, dispatch) {
         dispatch(updateHighlighted(newHighligthed, "update"));
     }
 }
-
-function loadFeatures(url, filter, add) {
+function dispatchFeaturesLoaded(reqId, add, max, state, config, dispatch) {
```
Comment (mbarto) [inline js/actions/featureselector.js]: The usual naming is featuresLoaded

Comment (offtherailz) [inline js/actions/featureselector.js]: This is not an action, but an internal utility method. featuresLoaded already exists as an action in this action.
